### PR TITLE
Add Category Filters to splash page

### PR DESCRIPTION
**Pull request by alexg-4mile**
https://user-images.githubusercontent.com/15178711/134708836-efefdfe1-629d-4879-8157-0573283cda04.mp4

Note: This PR points to the `alex/left-column` branch since I worked on top of it, but there should be no conflicts between those two and main.

### CODE REVIEW

**Comment by danchapman** [comment]
Code looks well done to me @alexg-4mile, I will let @elliot-at-looker review to see if he's ok with the config block especially. I have a few cosmetic changes that I want to request based on the mocks which I will put in a few more comments below.

**Comment by danchapman** [comment]
Screen Shot 2021-09-24 at 9 49 04 AM
 Per the mocks, could you position the numeric values towards the bottom of the ring. Given that we are seeing some percentages in the triple digits, it might be good to shrink the text size as well.

**Comment by danchapman** [comment]
Screen Shot 2021-09-24 at 9 49 37 AM
For the heading, please use bold, all caps, and shrink the text just a touch to match the mocks, and then give the header a bit more bottom padding as well.

**Comment by danchapman** [comment]
Screen Shot 2021-09-24 at 9 50 16 AM

Screen Shot 2021-09-24 at 9 57 19 AM

@alexg-4mile did you look for any short label fields?

@elliot-at-looker would it be possible for us to modify those category names, or add a short label field?

**Comment by alexg-4mile** [comment]
Made the small styling fixes:

image

Re shorter field labels, these were the shortest ones I could find in the looker instance. "Fashion Hoodies and Sweashirts" is long enough to cause 3 lines which causes the awkward padding. We could either 1) make each CategoryFilterItem wider, 2) add `text-overlow: ellipsis` to the CategoryFilterItem label, or 3) leave as is

**Comment by alexg-4mile** [comment]
Rebased+manually tested on top of the new `alex/yarn-lock` branch

**Comment by danchapman** [comment]
Looking better @alexg-4mile! The one last comment is can we left align the filter widget per the mocks, instead of a centered alignment:

Screen Shot 2021-09-29 at 4 07 25 PM

**Comment by alexg-4mile** [comment]
Fixed to left align. Had to hardcode the width of the category filter container because I was spending too much time trying to do it the "proper" way with flex/flex-grow, should appear fine for most 13inch screen users.

**Pull request merged**
